// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcSatZ3i9RfQqPttWRNPuui4NE6gAJ724',
    appId: '1:707748362187:web:4a35ed99be532ccca8e84e',
    messagingSenderId: '707748362187',
    projectId: 'expensetracker-12c31',
    authDomain: 'expensetracker-12c31.firebaseapp.com',
    storageBucket: 'expensetracker-12c31.firebasestorage.app',
    measurementId: 'G-95P9Z62W6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz8BzcIxLcEe7h7UlSte00hPEmBMPEpPE',
    appId: '1:707748362187:android:295b4e6191421d63a8e84e',
    messagingSenderId: '707748362187',
    projectId: 'expensetracker-12c31',
    storageBucket: 'expensetracker-12c31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-QH3hEaeKeuEsZlqxn1X7CMlNRWZp5Sw',
    appId: '1:707748362187:ios:e14d0fc7d2b51e2ea8e84e',
    messagingSenderId: '707748362187',
    projectId: 'expensetracker-12c31',
    storageBucket: 'expensetracker-12c31.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-QH3hEaeKeuEsZlqxn1X7CMlNRWZp5Sw',
    appId: '1:707748362187:ios:e14d0fc7d2b51e2ea8e84e',
    messagingSenderId: '707748362187',
    projectId: 'expensetracker-12c31',
    storageBucket: 'expensetracker-12c31.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcSatZ3i9RfQqPttWRNPuui4NE6gAJ724',
    appId: '1:707748362187:web:2e90cafcdfe6c063a8e84e',
    messagingSenderId: '707748362187',
    projectId: 'expensetracker-12c31',
    authDomain: 'expensetracker-12c31.firebaseapp.com',
    storageBucket: 'expensetracker-12c31.firebasestorage.app',
    measurementId: 'G-5D76GEPMSZ',
  );

}